---
- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Start Postgres
  become: true
  service:
    name: postgresql
    state: started
    enabled: true

- become: true
  become_user: postgres
  block:
    - name: Create PostgreSQL users
      postgresql_user:
        state: present
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        encrypted: yes

    - name: Create PostgreSQL database
      postgresql_db:
        state: present
        name: "{{ database_name }}"
        owner: "{{ database_user }}"

    - name: Create the shared extensions schema
      postgresql_schema:
        name: shared_extensions
        db: "{{ database_name }}"
        owner: "{{ database_user }}"

    - name: Add PostgreSQL extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "{{database_name}}"
        schema: shared_extensions
      with_items:
        - plpgsql
        - unaccent
        - pg_trgm
