---
- name: Make sure we have a '{{ deploy_group }}' group
  group:
    name: "{{ deploy_group }}"
    state: present

- name: Allow '{{ deploy_group }}' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ deploy_group }}'
    line: '%{{ deploy_group }} ALL=(ALL) NOPASSWD: ALL'

- name: Create the deploy user
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    state: present
    shell: /bin/bash

- name: Ensure correct permissions of deploy user home directory
  file:
    path: "{{ home_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0755
    state: directory

- name: Install SSH key
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', '{{ ssh_public_key_path }}') }}"
