- name: Install Tools
  become: true
  apt:
    state: latest
    update_cache: true
    name:
      - build-essential
      - cron
      - tmux
      - vim
      - htop
      - git-core
      - wget
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - curl
      - libcurl4-openssl-dev
      - libpq-dev
      - imagemagick
      - ruby-dev
      - shared-mime-info
      - policykit-1
