- name: Start DelayedJobs queue
  shell: "{{ fnm_command }} && {{ rvm_command }} && RAILS_ENV={{ env }} fnm exec bin/delayed_job -m -n 2 restart"
  args:
    executable: /bin/bash
    chdir: "{{ release_dir }}"
